---
authors:
  - Eric Ames (ericcames)
  - Mark Lowcher (mlowcher61)
dependencies:
  "ansible.posix": ">=2.1.0"
  "ansible.utils": ">=6.0.0"
  "ansible.platform": ">=2.6.20250924"
  "ansible.hub": ">=1.0.2"
  "ansible.controller": ">=4.7.1"
  "ansible.eda": ">=2.10.0"
  "infra.aap_configuration": ">=3.8.0"
license_file: LICENSE
name: f5_daily_demo
description: An f5 demo that can be run every day to show people how Ansible Automation Platform can be used to manage f5 devices.
namespace: ericcames
readme: README.md
repository: https://github.com/ericcames/aap.dailydemo.F5
issues: https://github.com/ericcames/aap.dailydemo.F5/issues
tags:
  - lab
  - cloud
  - aws
  - f5
  - dailydemo
  - automation
  - ansible
  - awesome
version: 1.0.0