---
- name: Patch my system
  hosts: tag_Type_ml_demo
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Upgrade all packages except sudo.x86_64
      ansible.builtin.dnf:
        name: "*"
        state: latest
        security: true
        bugfix: true
        update_only: true
        skip_broken: true
